version: '3'
services:
 
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./site/code:/code
      - ./site/site.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
  
  php:
    build: site/.
    volumes:
      - ./site/code:/code
    restart: on-failure
  